import type { Metadata } from "next";
import { Geist, Geist_Mono, Fira_Sans } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import Header from "./components/Header/Header";
import Footer from "./components/Footer/Footer";
import "rsuite/dist/rsuite-no-reset.min.css";
import { CustomProvider } from "rsuite";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const firaSans = Fira_Sans({
  display: "swap",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  adjustFontFallback: false,
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${firaSans.className} ${geistMono.variable} ${geistSans.variable} antialiased bg-ghostWhite text-black dark:bg-[#1b1b1b] dark:text-white`}
      >
        <CustomProvider>
          <Header />
          <Providers>{children}</Providers>
          <Footer />
        </CustomProvider>
      </body>
    </html>
  );
}
